topic_name_lidar: "/points_raw"
topic_name_radar: "/esr_can1_tracks"
box_filter_set:
  center: [9, 2, 0.5]
  cube_side_length: [1,1,10]
intensity_filter_set:
  lower_upper_bound: [20, 150]
target_size_set:
  model_type: triangle
  center_to_end_length: 0.6
  reflector_edge_length: 0.282843
edge_points_resolution: 20
T_lr:
  translation: [0.157272, 0.103420, 0]
  rotation: [33.5726,0,0]
sid: "0"
