topic_name_lidar: "/points_raw"
box_filter_set:
  center: [7, 5, 0]
  cube_side_length: [2,2,10]
intensity_filter_set:
  lower_upper_bound: [0, 150]
target_size_set:
  model_type: triangle
  center_to_end_length: 0.6
  reflector_edge_length: 0.282843
lidar_resolution_set:
  vertical_resolution: 1.33
  horizontal_resolution: 0.16

